#! /usr/bin/bash


# function to replace whitespace with '_'
_encode() {
  local string="$1"
  echo "${string//[[:space:]]/_}" | tr 'A-Z' 'a-z'

}


# Get current date in YYYY-MM-DD format
date=$(date +%Y-%m-%d)

# Prompt for frontmatter fields
echo "Let's get it, Tari🌃"
read -p "Title 🖋:" title
read -p "Summary 📜:" summary
read -p "Tags 🏷 (comma-separated): " tags
read -p "Canonical url🔗: " canonicalUrl



# create filename from the passed in title
filename=$(_encode "$title").mdx;
baseUrl="https://deantarisai.me/blog/";

# Create frontmatter
frontmatter=$(cat <<EOF
---
title: $title
date: $date
canonicalUrl: "$baseUrl$(_encode "$canonicalUrl")"
draft: true
tags: [$tags]
layout: PostSimple
summary: $summary
---
EOF
)


# direct the output to a file at the path stored by $filename
echo "$frontmatter" > data/blog/"$filename"

# track the file and make a commit. This last part is opinionated
git add . && git commit -a -m "New✨ post draft - $title  🖋." & echo "New✨ template for the post - $title. written 🖋."